config:
  packageIndividually: false
  profile: ${self:custom.stage}
  domain:
    url: "api.insights.example.com"
    certificate: "*.insights.example.com"

custom:
  verifyPriceHistoryEnabled: true
  verifyStatusChangeQueueEnabled: true
  sendEmailProtheusEnabled: true

environment:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
  NODE_ENV: "production"
  NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
  MONGODB_URI: ${ssm:/insights-platform/prod/MONGODB_URI}
  SECRET_TOKEN_EXPIRE: "24h"
  SECRET_TOKEN: ${ssm:/insights-platform/prod/JWT_SECRET}
  DEFINE_PASSWORD_TOKEN_EXPIRE: "2h"
  AZURE_API: ${ssm:/insights-platform/prod/AZURE_API}
  AZURE_CLIENT_ID: ${ssm:/insights-platform/prod/AZURE_CLIENT_ID}
  AZURE_CLIENT_SECRET_VALUE: ${ssm:/insights-platform/prod/AZURE_CLIENT_SECRET_VALUE}
  AZURE_TENANT_ID: ${ssm:/insights-platform/prod/AZURE_TENANT_ID}
  AZURE_RESOURCE: ${ssm:/insights-platform/prod/AZURE_RESOURCE}
  AZURE_USERNAME: ${ssm:/insights-platform/prod/AZURE_USERNAME}
  AZURE_PASSWORD: ${ssm:/insights-platform/prod/AZURE_PASSWORD}
  SITE_URL: "https://insights.example.com"
  EMBED_PBI_API_URL: ${ssm:/insights-platform/prod/EMBED_PBI_API_URL}
  INSIGHTS_ADMIN_CREDENTIALS: ${ssm:/insights-platform/prod/INSIGHTS_ADMIN_CREDENTIALS}
  AWS_SOURCE_EMAIL: "noreply@example.com"

deploymentBucket:
  name: serverless-deploy-insights-prd
  blockPublicAccess: true
  serverSideEncryption: AES256

vpc:
  securityGroupIds:
    - sg-087631880c57450dd
  subnetIds:
    - subnet-07718420f674f2d75

