on:
  push:
    branches: [main, qa]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  Security:
    uses: adhfoundation/gha-templates/.github/workflows/security.yml@main
    secrets:
      SONAR_FOUNDATION_TOKEN: ${{ secrets.SONAR_FOUNDATION_TOKEN }}
